// Les maladies du dos affichées dans l'application. Pour en ajouter, copie une ligne et change les textes.
const Z={
cervical:{t:"Cou (cervicales)",f:[
{n:"Cervicalgie",c:"Muscles du cou tendus par une mauvaise posture, l'écran du téléphone ou un oreiller trop haut.",e:"Rotations lentes de la tête, étirement des épaules, 3 fois 20 secondes. Fais des pauses toutes les 30 minutes devant l'écran.",a:"Douleur qui descend dans le bras, fourmillements, maux de tête violents après un choc."},
{n:"Torticolis",c:"Contracture brutale des muscles du cou, souvent après une nuit dans une mauvaise position ou un courant d'air. La tête reste penchée d'un côté.",e:"Chaleur douce sur le cou, mouvements lents sans forcer. Ne reste pas immobile. Cela passe souvent en quelques jours.",a:"Fièvre avec raideur du cou et fort mal de tête, douleur après un choc, ou aucune amélioration après une semaine."},
{n:"Névralgie cervico-brachiale",c:"Un nerf du cou est irrité par de l'arthrose ou une petite hernie. La douleur descend dans l'épaule et le bras, parfois jusqu'à la main, avec des fourmillements.",e:"Évite les positions qui augmentent la douleur (cou en arrière, charges lourdes). Mouvements très doux du cou. Un avis médical est conseillé.",a:"Perte de force dans le bras ou la main, douleur très forte qui ne passe pas."},
{n:"Arthrose cervicale",c:"Usure des articulations du cou avec l'âge. Raideur, craquements, douleur surtout le matin ou en fin de journée.",e:"Rotations et inclinaisons lentes, marche, natation douce. Garde le cou au chaud.",a:"Vertiges forts, fourmillements dans les deux bras, difficulté à marcher."},
{n:"Cou du téléphone (text neck)",c:"La tête penchée vers le téléphone pendant des heures fatigue beaucoup les muscles du cou et du haut du dos.",e:"Monte l'écran à hauteur des yeux, fais une pause toutes les 20 à 30 minutes, rentre doucement le menton, étire les épaules.",a:"Douleur qui descend dans le bras, fourmillements, maux de tête fréquents."},
{n:"Coup du lapin (après un choc)",c:"Le cou est brusquement étiré après un accident, par exemple de voiture ou de moto. La douleur et la raideur peuvent apparaître le lendemain.",e:"Un avis médical est conseillé après un choc. Ensuite, bouge le cou doucement dès que possible, avec de la chaleur. Ne reste pas immobile.",a:"Très forte douleur, perte de force dans un bras, mal de tête violent, vomissements, vertiges."}]},
dorsal:{t:"Milieu du dos (dorsales)",f:[
{n:"Dorsalgie",c:"Position assise prolongée, dos arrondi, stress, port de charges mal réparti.",e:"Ouvre la poitrine bras en croix, étirement du dos à quatre pattes (dos rond puis creux), respiration lente.",a:"Douleur à la poitrine, essoufflement, douleur la nuit qui ne passe pas."},
{n:"Scoliose",c:"La colonne est déviée sur le côté et un peu tournée. Elle apparaît souvent à l'adolescence et fait rarement très mal.",e:"Activité physique régulière : natation, marche, étirements. Un médecin ou un kinésithérapeute doit suivre l'évolution.",a:"Déformation qui augmente vite chez un enfant ou un adolescent, douleur forte, gêne pour respirer."},
{n:"Dos rond (cyphose)",c:"Haut du dos trop arrondi à cause de la posture (écran, travail assis), de l'âge ou de muscles du dos faibles.",e:"Ouvre la poitrine, rapproche les omoplates, renforce le haut du dos, redresse-toi toutes les 30 minutes.",a:"Dos qui se courbe vite chez une personne âgée, douleur forte après une chute."},
{n:"Tassement vertébral",c:"Une vertèbre s'affaisse, souvent parce que les os sont fragiles (ostéoporose), parfois après une petite chute.",e:"Avis médical nécessaire. Marche douce, évite de porter lourd et de te pencher brusquement en avant.",a:"Douleur brutale dans le dos après une chute, même légère, surtout après 50 ans : consulte vite."},
{n:"Névralgie intercostale",c:"Un nerf entre deux côtes est irrité. La douleur fait comme une ceinture et augmente en respirant, en toussant ou en se tournant.",e:"Chaleur douce, respiration lente et mouvements doux. Cela passe souvent en quelques jours ou semaines.",a:"Douleur à la poitrine avec essoufflement, sueurs ou malaise : urgence. Aussi : petites cloques sur la peau (zona) ou fièvre."},
{n:"Blocage de côte",c:"Une côte se bloque à l'endroit où elle touche la colonne. La douleur est dans le dos et augmente en respirant à fond.",e:"Respirations lentes et profondes, mobilité douce du dos, chaleur. Un kinésithérapeute peut aider.",a:"Douleur à la poitrine, essoufflement, douleur après un choc violent."},
{n:"Contracture du haut du dos",c:"Le muscle entre le cou et l'épaule est tendu par le stress, la posture ou un sac porté toujours du même côté.",e:"Étirements du cou et des épaules, chaleur, relâche les épaules, change de côté pour porter ton sac.",a:"Douleur dans le bras gauche avec essoufflement ou douleur à la poitrine : urgence."}]},
lombaire:{t:"Bas du dos (lombaires)",f:[
{n:"Lombalgie",c:"Muscles ou articulations du bas du dos surmenés : effort, sédentarité, mauvaise posture.",e:"Marche douce, genoux ramenés vers la poitrine allongé, bascule du bassin. Reste actif, le repos complet aggrave souvent la douleur.",a:"Douleur après une chute, fièvre, perte de force dans les jambes."},
{n:"Lumbago (tour de reins)",c:"Douleur brusque et vive en bas du dos après un faux mouvement ou un effort. Il est difficile de se redresser.",e:"Reste actif en douceur, marche courte, chaleur sur le bas du dos. Évite de rester couché toute la journée. Cela guérit souvent en quelques jours à deux semaines.",a:"Douleur après une chute, fièvre, perte de force ou difficulté à uriner."},
{n:"Sciatique",c:"Nerf sciatique irrité : douleur qui descend de la fesse vers la jambe, parfois jusqu'au pied.",e:"Marche courte et régulière, étirement doux des fesses. Évite de porter lourd et de rester assis longtemps.",a:"Jambe qui s'affaiblit, engourdissement près des parties intimes, difficulté à uriner."},
{n:"Hernie discale",c:"Un disque entre deux vertèbres appuie sur un nerf. Douleur au dos et parfois à la jambe.",e:"Demande l'avis d'un médecin avant tout exercice. En général : marche douce et pas de charges lourdes.",a:"Faiblesse d'une jambe, douleur qui augmente malgré le repos."},
{n:"Arthrose lombaire",c:"Usure des articulations du bas du dos, fréquente après 50 ans. Raideur le matin, douleur après l'effort.",e:"Marche régulière, natation, étirements doux, poids stable.",a:"Douleur de nuit qui réveille, perte de force dans les jambes."},
{n:"Canal lombaire étroit",c:"Le passage des nerfs se rétrécit avec l'âge. Les jambes deviennent lourdes ou douloureuses en marchant, et cela passe quand on s'assoit ou qu'on se penche en avant.",e:"Marche par petites étapes, vélo (position penchée en avant). Un avis médical est conseillé.",a:"Faiblesse des jambes, difficulté à uriner, perte de sensibilité entre les jambes."},
{n:"Douleur sacro-iliaque",c:"L'articulation entre le bas du dos et le bassin est irritée, souvent après un faux mouvement ou pendant la grossesse. La douleur est d'un côté, vers la fesse.",e:"Évite de rester longtemps debout sur une jambe ou les jambes croisées. Marche douce, étirements doux des fesses.",a:"Fièvre, douleur très forte la nuit, jambe qui s'affaiblit."},
{n:"Douleur du coccyx",c:"Douleur tout en bas du dos, surtout assis. Souvent après une chute sur les fesses ou une longue position assise.",e:"Utilise un coussin en forme de U, change souvent de position, évite les sièges durs.",a:"Douleur après une chute violente, fièvre, difficulté à uriner ou à aller aux toilettes."},
{n:"Spondylarthrite",c:"Maladie inflammatoire du bas du dos et du bassin, souvent chez les jeunes adultes. La douleur est pire la nuit et le matin, et diminue avec le mouvement.",e:"Le mouvement aide : étirements, natation, marche. Un médecin (rhumatologue) doit confirmer et suivre.",a:"Douleur du dos depuis plus de 3 mois avant 45 ans, avec raideur le matin de plus de 30 minutes : consulte."},
{n:"Lombalgie chronique",c:"Douleur qui dure depuis plus de 3 mois. Elle est souvent liée au manque d'activité, au stress et à la peur de bouger.",e:"Activité physique douce et progressive : marche, natation, renforcement. Dors suffisamment. Un kinésithérapeute peut te guider.",a:"Perte de poids sans raison, fièvre, douleur qui te réveille la nuit."},
{n:"Spondylolisthésis",c:"Une vertèbre glisse un peu en avant sur celle du dessous. Elle se voit chez des sportifs jeunes ou avec l'âge. La douleur augmente quand on se cambre.",e:"Avis médical conseillé. Évite de te cambrer à fond, marche douce, renforcement doux du ventre.",a:"Faiblesse d'une jambe, engourdissement, difficulté à uriner."},
{n:"Syndrome du piriforme",c:"Un muscle profond de la fesse irrite le nerf sciatique. La douleur est dans la fesse, parfois dans la jambe, surtout assis.",e:"Étirement doux de la fesse (couché, cheville sur le genou opposé), marche, change souvent de position assise.",a:"Faiblesse de la jambe, fièvre, douleur très forte."},
{n:"Mal de dos de grossesse",c:"Le poids du ventre, les hormones qui assouplissent les ligaments et le changement de posture fatiguent le bas du dos.",e:"Marche, natation, dors sur le côté avec un coussin entre les genoux. Demande conseil à ta sage-femme pour une ceinture de maintien.",a:"Saignements, fièvre, douleur régulière ou forte du ventre, perte de liquide."},
{n:"Mal de dos du travail physique",c:"Port répété de charges lourdes ou gestes répétés en étant penché. Le bas du dos se fatigue petit à petit.",e:"Plie les genoux, garde la charge près de ton corps, ne tourne pas le dos en portant, fais des pauses et étire-toi.",a:"Douleur forte après un effort, jambe qui s'affaiblit ou fourmille."},
{n:"Douleur venant des reins",c:"La douleur ne vient pas du dos mais d'un rein : très vive d'un côté, sous les côtes, elle descend vers le bas du ventre.",e:"Le mouvement ne la change pas. Ne prends pas de médicament au hasard et consulte vite un médecin.",a:"Fièvre, sang dans les urines, vomissements, douleur très forte : consulte tout de suite."}]}
};
